# Generated by Django 5.2.7 on 2025-10-15 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('drive_id', models.CharField(max_length=255)),
                ('enlace_drive', models.URLField()),
                ('miniatura', models.ImageField(blank=True, null=True, upload_to='miniaturas/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
