# Generated by Django 5.2.7 on 2025-10-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentaciones', '0002_presentacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentacion',
            options={'ordering': ['-fecha_subida']},
        ),
        migrations.AddField(
            model_name='presentacion',
            name='miniatura_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
