# Generated by Django 5.2.7 on 2025-10-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentaciones', '0003_alter_presentacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentacion',
            name='archivo_local',
            field=models.FileField(blank=True, null=True, upload_to='presentaciones/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='presentacion',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='presentacion',
            name='ubicacion',
            field=models.CharField(choices=[('drive', 'Google Drive'), ('local', 'Servidor Local')], default='drive', max_length=10),
        ),
        migrations.AlterField(
            model_name='presentacion',
            name='drive_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='presentacion',
            name='enlace_drive',
            field=models.URLField(blank=True, null=True),
        ),
    ]
